const searchTypes = {
	FIND_LOCATION_START: 'FIND_LOCATION_START',
	FIND_LOCATION_SUCCESS: 'FIND_LOCATION_SUCCESS',
	FIND_LOCATION_FAILURE: 'FIND_LOCATION_FAILURE',
	CLEAR_LOCATIONS: 'CLEAR_LOCATIONS',
};

export default searchTypes;
