const detailsTypes = {
	GET_WEATHER_START: 'GET_WEATHER_START',
	GET_WEATHER_SUCCESS: 'GET_WEATHER_SUCCESS',
	GET_WEATHER_FAILURE: 'GET_WEATHER_FAILURE',
	GET_DAILY_START: 'GET_DAILY_START',
	GET_DAILY_SUCCESS: 'GET_DAILY_SUCCESS',
	GET_DAILY_FAILURE: 'GET_DAILY_FAILURE',
};

export default detailsTypes;
